<?php

/**
 * Implementation of hook_perm().
 */
function hosting_expiry_date_perm() {
  $perms = array(
    'set site expiry dates');
  return $perms;
}

/**
 * Implementation of hook_menu().
 */
function hosting_expiry_date_menu() {
  $items = array();
  $items['node/%hosting_expiry_date_node/expiry'] = array(
    'title' => t('Expiry dates'),
    'description' => t('Site expiry date(s)'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_expiry_date_site_form', 1),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('set site expiry dates'),
    'weight' => 1,
  );
  return $items;
}

/**
 * Wildcard loader function to limit the expiry dates tab to just site nodes
 */
function hosting_expiry_date_node_load($arg) {
  if (!is_numeric($arg)) {
    return FALSE;
  }
  if ($node = node_load($arg)) {
    if (in_array($node->type, array('site'))) {
      return $arg;
    }
  }
  return FALSE;
}

/**
 * Form where we collect expiry dates for sites
 *
 * @param $nid
 *   Node ID of the site
 */
function hosting_expiry_date_site_form($form_state, $nid) {
  drupal_set_title(t('Expiry Dates for') . ' ' . node_load($nid)->title);
  $form = array();
  $form['intro'] = array(
    '#value' => t('Set expiry dates for this site. The site sill be disabled or deleted on these dates.'),
  );
 
  $form['Disable'] = array(
    '#type' => 'fieldset',
    '#title' => t('Disable site'),
  );

  $form['Disable']['disable_active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Automatically disable this site?'),
    '#default_value' => (bool) hosting_expiry_date_lookup($nid, 'disable'),
  );

  $form['Disable']['disable_date'] = array(
    '#type' => 'date',
    '#title' => t('Disable date'),
    '#default_value' => hosting_expiry_date_default($nid, 'disable', '30'),
  );

  $form['Delete'] = array(
    '#type' => 'fieldset',
    '#title' => t('Delete site'),
  );

  $form['Delete']['delete_active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Automatically delete this site?'),
    '#default_value' => (bool) hosting_expiry_date_lookup($nid, 'delete'),
  );

  $form['Delete']['delete_date'] = array(
    '#type' => 'date',
    '#title' => t('Delete date'),
    '#default_value' => hosting_expiry_date_default($nid, 'delete', '30'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

/**
 * Validate our form.
 */
function hosting_expiry_date_site_form_validate($form, &$form_state) {
  // TODO: find a better way to do this
  $disable_date = mktime(0, 0, 0, $form_state['values']['disable_date']['month'], $form_state['values']['disable_date']['day'], $form_state['values']['disable_date']['year']);
  $delete_date = mktime(0, 0, 0, $form_state['values']['delete_date']['month'], $form_state['values']['delete_date']['day'], $form_state['values']['delete_date']['year']);
  $today = time();

  // ensure that expiry dates are in the future
  if ($disable_date < $today && $form_state['values']['disable_active'] != '0') {
    form_set_error($form['Disable']['disable_date'], '<em>' . $form['Disable']['disable_date']['#title'] .'</em>' . t(' must be set to a future date.'));
  }
  if ($delete_date < $today && $form_state['values']['delete_active'] != '0') {
    form_set_error($form['Delete']['delete_date'], '<em>' . $form['Delete']['delete_date']['#title'] . '</em>' . t(' must be set to a future date.'));
  }
}

/**
 * Implementation of hook_form_submit().
 */
function hosting_expiry_date_site_form_submit($form, &$form_state) {
  $nid = $form['#parameters'][2];
  
  db_query('DELETE FROM {hosting_expiry_date_dates} WHERE site_nid = %d', $nid);
  
  if ($form_state['values']['disable_active'] == '1') {
    $disable_date = date_create_from_format('Y-m-d', $form_state['values']['disable_date']['year'] . '-' . $form_state['values']['disable_date']['month'] . '-' . $form_state['values']['disable_date']['day']);
    db_query('INSERT INTO {hosting_expiry_date_dates} (site_nid, expiry_date, action) VALUES (%d, "%s", "disable")', $nid, $disable_date->format('Y-m-d H:i:s'));
    }
  if ($form_state['values']['delete_active'] == '1') {
    $delete_date = date_create_from_format('Y-m-d', $form_state['values']['delete_date']['year'] . '-' . $form_state['values']['delete_date']['month'] . '-' . $form_state['values']['delete_date']['day']);
    db_query('INSERT INTO {hosting_expiry_date_dates} (site_nid, expiry_date, action) VALUES (%d, "%s", "delete")', $nid, $delete_date->format('Y-m-d H:i:s'));
    }
}

/**
 * Get the expiry date for a given node
 *
 * @param $nid
 *   Node ID of the site
 * @param $action
 *   'disable' or 'delete'
 *
 * @return
 *   If set, the expiry date set for $action. Otherwise, FALSE.
 */
function hosting_expiry_date_lookup($nid, $action) {
  $date = db_result(db_query('SELECT expiry_date FROM {hosting_expiry_date_dates} WHERE site_nid = %d AND action = "%s"',$nid, $action));
  if (!empty($date)) {
    return $date;
  }
  else {
    return FALSE;
  }
}

/**
 * Format an expiry date for display in a form
 *
 * @param $nid
 *   Node ID of the site
 * @param $action
 *   'disable' or 'delete'
 * @param $offset
 *   The number of day in the future to set the default date
 *
 * @return
 *   If set, the expiry date set for $action, as an array. Otherwise, today's
 *   date + $offset, as an array.
 */
function hosting_expiry_date_default($nid, $action, $offset = '0') {
  $date = date_create_from_format('Y-m-d H:i:s', hosting_expiry_date_lookup($nid, $action));
  if (empty($date)) {
    $today = new DateTime();
    $date = date_modify($today, '+' . $offset . ' days');
  }
  return array(
    'year' => $date->format('Y'),
    'month' => $date->format('n'), //no leading zeros
    'day' => $date->format('d'),
  );
}

